### ISSUE TITLE
Why haha 2.0.4 includes an old version of perflib

### ISSUE THREAD

**Issue by fvdcx** [square/haha#25]
@pyricau  Appologies first as this might be a beginner's question.

I saw Snapshot.computeDominators method in haha 2.0.4 is a very old version(the old version had a TODO: "Break dominator computation into fixed chunks, because it can be unbounded/expensive.").

this code snippets is from haha 2.0.4
![image](https://user-images.githubusercontent.com/3365271/53934580-57b66780-40de-11e9-9e95-d1aa01739bb6.png)

Actually AOSP perflib had already a fix in 2015, see this: https://android.googlesource.com/platform/tools/base/+/72b27494b12ef02e0a9435a9b6451c0e61461074%5E%21/#F6

![image](https://user-images.githubusercontent.com/3365271/53934287-3903a100-40dd-11e9-8e57-69ef56efa46f.png)

**Comment by pyricau** [comment]
We're blocked on updating perlib, see #22
