### ISSUE TITLE
Incorrect retain size and native size

### ISSUE THREAD

**Issue by datpt91** [square/haha#26]
After dump hprof file:
snapshot = Snapshot.createSnapshot(buffer);
snapshot.computeDomintors();
The param values shallowSize, instanceCount are correct; but totalRetainedSize, nativeSize are incorrect compare to hprof(which show in Android Studio).

**Comment by pyricau** [comment]
HAHA is a repackaging of the exact same code that runs in Android Studio (perflib), so it's hard to imagine the same code would give different results.

Also worth noting that this project will not be maintained from now on as it was built for LeakCanary and LeakCanary now has its own heap dump parser.
