### ISSUE TITLE
Add correct sources to maven's source jar

### ISSUE THREAD

**Issue by dandc87** [square/haha#7]
The current source jar contains classes under their original packages, not the renamespaced one (e.g. `com/android/tools/perflib/heap/ArrayInstance.java` instead of `com/squareup/haha/perflib/ArrayInstance.java`).

This means that IntelliJ shows decompiled classes instead of real sources, and people who want to make source modifications can't rebuild from the source jar.

**Comment by pyricau** [comment]
Sorry, somehow I wasn't watching this repo.

**Comment by pyricau** [comment]
Fixed by #8
