### ISSUE TITLE
OOM when trying to compute the dominators

### ISSUE THREAD

**Issue by Maragues** [square/haha#9]
LeakCanary 1.4-beta is showing this "Leak analysis failed" that seems to come from *haha*

![image](https://cloud.githubusercontent.com/assets/655970/13142962/fb1c8c9e-d640-11e5-8b7c-d861db019e4d.png)

See https://github.com/square/leakcanary/issues/423

**Comment by Maragues** [comment]
The stacktrace is different, but it seems to com from *haha*. See attached *.hprof*
 
![image](https://cloud.githubusercontent.com/assets/655970/13181689/91a8133e-d72e-11e5-8d91-d2edad3b0b63.png)

[2016-02-19_16-23-47_654.hprof.zip](https://github.com/square/haha/files/138310/2016-02-19_16-23-47_654.hprof.zip)

**Comment by pyricau** [comment]
This is a heap dump from Android M, right?

**Comment by pyricau** [comment]
This is probably the same as https://github.com/square/leakcanary/issues/223
